language: ruby

rvm:
  - 2.3.1

addons:
  apt:
    packages:
      - imagemagick

install: gem install jekyll html-proofer s3_website

script:
  - jekyll build
  - htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# use container infrastructure on travis
sudo: false

before_deploy:
  - mv s3_website.yml.example s3_website.yml
deploy:
  skip_cleanup: true
  provider: script
  script: s3_website push
  on:
    branch: master
