language: ruby

rvm:
  - 2.3.1

addons:
  apt:
    packages:
      - imagemagick

install: gem install jekyll html-proofer

script:
  - jekyll build
  - htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# use container infrastructure on travis
sudo: false
