language: ruby

rvm:
  - 2.3.1

addons:
  apt:
    packages:
      - imagemagick

install: bundle install

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --disable-external ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# use container infrastructure on travis
sudo: false

before_deploy:
  - mv s3_website.yml.example s3_website.yml
deploy:
  skip_cleanup: true
  provider: script
  script: 'PATH="${TRAVIS_BUILD_DIR}/bin:$PATH" rvm "$TRAVIS_RUBY_VERSION" do bundle exec s3_website push'
  on:
    branch: master
